[service]
name = "tricertask"
#license_key = "E6BC079C-70634B2E-80F9B871-FEA8F2E3"
port = 5555
imports = [
  "./todo.toml",
  "./todo_history.toml",
  "./todo_access.toml",
  "./user_connections.toml",
  "./user.toml",
  "./notification.toml"
]

[service.cors]
allow_headers = [
  "Authorization", 
  "Content-Type", 
]

[[service.data_sources]]
[service.data_sources.SQL]
name = "triceratask_ds"
uri = "$TRICERATASK_SQL_URI"
dialect = "SQLITE"
#TODO: Rename the extension to uuid
sqlite_extensions = ["$TRICERATASK_SQLITE_EXTENSIONS"]
migrations_path = "$TRICERATASK_MIGRATIONS_PATH"

# [service.data_sources.SQL]
# name = "triceratask_ds"
# uri = "postgre://root:rootroot@localhost:5432/triceratask"
# dialect = "POSTGRES"

# [service.data_sources.SQL]
# name = "triceratask_ds"
# dialect = "MYSQL"
# uri = "mysql://root:rootroot1234@localhost:3306/triceratask"

[service.auth]
requesting_party = "$TRICERATASK_RP" #"localhost"
requesting_party_name = "$TRICERATASK_RPN" #"triceratask.com"
requesting_party_origin = "$TRICERATASK_RPO" #"http://localhost:5173" #Origin of the client. http://localhost:5173
data_source = "triceratask_ds"
private_key = "$TRICERATASK_PRIVATE_KEY" # Generate a private key.

[[service.guards]]
name = "require_user"
if_expr = '''
  len(context("user.id")) == 0 
'''
then_msg = "You must be logged in to perform this action."
[[service.guards.context]]
entity_name = "user"
query = '''
  {
    "get_users_input": {
      "query": {
        "uuid": {{user_uuid}}
      } 
    }
  }
'''
variables = [
  [ "{{user_uuid}}", "token_data(\"user_uuid\")" ]
]
