[[entities]]
name = "notification"
required = true
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"], exclude_from_output = true },
  { name = "uuid", scalar = "UUID", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "user", scalar = "Int", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"], as_type = "user", join_on = "id", eager = true },
  { name = "notification_message", scalar = "Int", required = true, as_type = "notification_message", join_on = "id" },
  { name = "todo", scalar = "Int", required = false, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"], as_type = "todo", join_on = "id", eager = true },
  { name = "read", scalar = "Boolean", required = true },
  { name = "created_at", scalar = "DateTime", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "updated_at", scalar = "DateTime", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "created_by", scalar = "Int", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"], as_type = "user", join_on = "id" }
]

[[entities]]
name = "notification_message"
required = true
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"], exclude_from_output = true },
  { name = "identifier", scalar = "String", required = true },
  { name = "message", scalar = "String", required = true },
]
