[[entities]]
name = "todo_history"
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"]  },
  { name = "uuid", scalar = "String", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "todo_uuid", scalar = "String", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "created_by", scalar = "String", required = true, exclude_from_input = ["UpdateOne", "UpdateMany"] },
  { name = "created_at", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "property", scalar = "String", required = true },
  { name = "old_value", scalar = "String", required = false },
  { name = "new_value", scalar = "String", required = false },
]

[[entities.guards]]
name = "Permissions Error"
if_expr = """
  root_key = if(contains(("FindOne", "FindMany", "InternalType"), resolver_type()), "query", "values");
  !every(input(root_key, "created_by"), token_data("user_uuid"))
"""
then_msg = "You may not access this todo's history."
