name = "todo"
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"]  },
  { name = "uuid", scalar = "String", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "title", scalar = "String", required = true },
  { name = "description", scalar = "String", required = true },
  { name = "completed", scalar = "Boolean", required = true },
  { name = "created_at", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "updated_at", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "completed_at", scalar = "String", exclude_from_input = ["All"] },
  { name = "created_by", scalar = "String", required = true, exclude_from_input = ["UpdateOne", "UpdateMany"], as_type = "user", join_on = "uuid" },
  { name = "updated_by", scalar = "String", required = true },
  { name = "completed_by", scalar = "String", exclude_from_input = ["All"] },
  { name = "goal_date", scalar = "String" },
  { name = "history", scalar = "String", as_type = "todo_history", list = true, exclude_from_input = ["All"], join_on = "todo_uuid", join_from = "uuid" }
]

[service.entities.data_source]
from = "triceratask_ds"
[service.entities.data_source.resolvers]
[service.entities.data_source.resolvers.find_one]
[[service.entities.data_source.resolvers.find_one.guards]]
name = "Permissions Error"
if_expr = "token_data(\"user_uuid\") != input(\"created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

[service.entities.data_source.resolvers.find_many]
[[service.entities.data_source.resolvers.find_many.guards]]
name = "Permissions Error"
if_expr = "token_data(\"user_uuid\") != input(\"created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

[service.entities.data_source.resolvers.create_one]
[[service.entities.data_source.resolvers.create_one.guards]]
name = "Permissions Error"
if_expr = "token_data(\"user_uuid\") != input(\"created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

[service.entities.data_source.resolvers.update_one]
[[service.entities.data_source.resolvers.update_one.guards]]
name = "Permissions Error"
if_expr = "token_data(\"user_uuid\") != input(\"query.created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

[service.entities.data_source.resolvers.update_many]
[[service.entities.data_source.resolvers.update_many.guards]]
name = "Permissions Error"
if_expr = "token_data(\"user_uuid\") != input(\"query.created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

