[[entities]]
name = "todo_access"
required = true
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"] },
  { name = "uuid", scalar = "UUID", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "todo_id", scalar = "Int", required = true, as_type = "todo", join_on = "id", exclude_from_input = ["All"], default_value = "context(\"todo.id\")" },
  { name = "todo_uuid", scalar = "UUID", required = true, exclude_from_output = true, exclude_from_input = ["UpdateOne", "UpdateMany"] },
  { name = "user_uuid", scalar = "UUID", required = true, as_type = "user", join_on = "uuid" },
  { name = "view", scalar = "Boolean", required = true },
  { name = "edit", scalar = "Boolean", required = true },
  { name = "revoked", scalar = "Boolean", required = true }
]

[entities.data_source]
from = "triceratask_ds"
[[entities.data_source.resolvers.create_one.guards]]
name = "Not Exists"
if_expr = '''
  todo_id = context("todo.id");
  len(todo_id) == 0
'''
then_msg = "Todo does not exist"
[[entities.data_source.resolvers.create_one.guards.context]]
entity_name = "todo"
query = '''
  {
    "get_todos_input": {
      "query": {
        "AND": {{uuid}}
      }
    }
  }
'''
variables = [
  ["{{uuid}}", "input(\"values\", \"todo_uuid\")"]
]

