[[entities]]
name = "todo"
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"]  },
  { name = "uuid", scalar = "String", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "title", scalar = "String", required = true },
  { name = "description", scalar = "String", required = true },
  { name = "completed", scalar = "Boolean", required = true },
  { name = "created_at", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "updated_at", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "completed_at", scalar = "String", exclude_from_input = ["All"] },
  { name = "created_by", scalar = "String", required = true, exclude_from_input = ["UpdateOne", "UpdateMany"], as_type = "user", join_on = "uuid" },
  { name = "updated_by", scalar = "String", required = true },
  { name = "completed_by", scalar = "String", exclude_from_input = ["All"] },
  { name = "goal_date", scalar = "String" },
  { name = "history", scalar = "String", as_type = "todo_history", list = true, exclude_from_input = ["All"], join_on = "todo_uuid", join_from = "uuid" }
]

[[entities.guards]]
name = "Permissions Error"
if_expr = """
  root_key = if(contains(("FindOne", "FindMany", "UpdateMany"), resolver_type()), "query", "values");
  !every(input(root_key, "created_by"), token_data("user_uuid"))
"""
then_msg = "You may not access this todo."

