[[entities]]
name = "todo"
required = true
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"], exclude_from_output = true  },
  { name = "uuid", scalar = "UUID", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "title", scalar = "String", required = true },
  { name = "description", scalar = "String", required = true },
  { name = "completed", scalar = "Boolean", required = true },
  { name = "created_at", scalar = "DateTime", required = true, exclude_from_input = ["All"] },
  { name = "updated_at", scalar = "DateTime", required = true, exclude_from_input = ["All"] },
  { name = "completed_at", scalar = "DateTime", exclude_from_input = ["All"] },
  { name = "created_by", scalar = "Int",  exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"], as_type = "user", join_on = "id", default_value = "if(resolver_type() == \"CreateOne\", context(\"user.id\"), ())" },
  { name = "updated_by", scalar = "Int", required = true , exclude_from_input = ["All"], default_value = "context(\"user.id\")" },
  { name = "completed_by", scalar = "Int", exclude_from_input = ["All"] },
  { name = "goal_date", scalar = "DateTime" },
  { name = "history", scalar = "Int", as_type = "todo_history", list = true, exclude_from_input = ["All"], join_on = "todo", join_from = "id" },
  { name = "access", scalar = "Int", as_type = "todo_access", list = true, required = true, join_on = "todo", join_from = "id", eager = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] }
]

[entities.data_source]
from = "triceratask_ds"

[[entities.data_source.resolvers.find_one.guards]]
name = "require_access_user_uuid"
if_expr = '''
  every(input("query", "access.user.uuid"), token_data("user_uuid")) || len(input("query", "access.user.uuid")) == 0
'''
then_msg = "You do not have permission to view this task. Provide input value `acceess.user.uuid`."
[[entities.data_source.resolvers.find_one.guards]]
name = "require_access_revoked"
if_expr = '''
  contains(input("query", "access.revoked"), "true")
'''
then_msg = "You do not have permission to view this task. Provide input value `acceess.revoked` as a false value."

[[entities.data_source.resolvers.find_many.guards]]
name = "require_access_user_uuid"
if_expr = '''
  every(input("query", "access.user.uuid"), token_data("user_uuid")) || typeof(input("query", "access.user.uuid")) != "tuple"
'''
then_msg = "You do not have permission to view this task. Provide input value `acceess.user.uuid`."

[[entities.data_source.resolvers.find_many.guards]]
name = "require_access_revoked"
if_expr = '''
  revoked = ("true", "true"); // placeholder
  revoked = if(typeof(input("query", "access.revoked")) == "empty", ("true", "true"), input("query", "access.revoked"));
  contains(revoked, "true")
'''
then_msg = "You do not have permission to view this task. Provide input value `acceess.revoked` as a false value."

[[entities.data_source.resolvers.update_many.guards]]
name = "not_found"
if_expr = '''
  todo_uuids = input("query", "uuid");
  todos = context("todo.id");
  len(todo_uuids) != len(todos)
'''
then_msg = "Todo not found."
[[entities.data_source.resolvers.update_many.guards.context]]
entity_name = "todo"
query = '''
  {
    "get_todos_input": {
      "query": {
        "OR": {{uuid}}
      } 
    }
  }
'''
variables = [
  [ "{{uuid}}", "input(\"query\", \"uuid\")" ]
]

[[entities.data_source.resolvers.update_many.guards]]
name = "access_denied"
if_expr = '''
  is_edit = len(input("values", "title")) > 0 || len(input("values", "description")) > 0 || len(input("values", "goal_date")) > 0;
  is_manage = len(input("values", "title")) == 0 && len(input("values", "description")) == 0 && len(input("values", "goal_date")) == 0;
  todo_uuids = input("query", "uuid");
  todo_edit_acesses = context("todo_access.edit");
  block_edit = is_edit && (len(todo_uuids) != len(todo_edit_acesses) || !every(todo_edit_acesses, true));
  todo_manage_acesses = context("todo_access.manage");
  block_manage = is_manage && (len(todo_uuids) != len(todo_manage_acesses) || !every(todo_manage_acesses, true));
  block_edit || block_manage
'''
then_msg = "You do not have permission to update this task."
[[entities.data_source.resolvers.update_many.guards.context]]
entity_name = "todo_access"
query = '''
  {
    "get_todo_accesss_input": {
      "query": {
        "OR": {{todo}},
        "AND": [{ "AND": [{ "user": { "AND": {{id}} } }], "OR": [{ "edit": true }, { "manage": true }] }]
      } 
    }
  }
'''
variables = [
  [ "{{id}}", "context(\"user.id\")" ],
  [ "{{todo}}", "context(\"todo.id\")" ]
]
