[[entities]]
name = "todo_access"
required = true
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"] },
  { name = "todo_uuid", scalar = "UUID", required = true, as_type = "todo", join_on = "uuid" },
  { name = "user_uuid", scalar = "UUID", required = true, as_type = "user", join_on = "uuid" },
  { name = "view", scalar = "Boolean", required = true },
  { name = "edit", scalar = "Boolean", required = true },
]
