[[entities]]
name = "todo_history"
required = true
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"]  },
  { name = "uuid", scalar = "UUID", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "todo", scalar = "Int", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "created_by", scalar = "Int", required = true, exclude_from_input = ["UpdateOne", "UpdateMany"] },
  { name = "created_at", scalar = "DateTime", required = true, exclude_from_input = ["All"] },
  { name = "property", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "old_value", scalar = "String", required = false  },
  { name = "new_value", scalar = "String", required = false },
]

