[service]
name = "todos"
port = 5555

[service.cors]
allow_methods = [{method = "POST"}]
allow_headers = ["Authorization", "Content-Type"]

[[service.data_sources]]
[service.data_sources.SQL]
name = "triceratask_ds"
uri = "sqlite:/home/nickisyourfan/Desktop/DEV/my-todo-app/api/todos.db"
dialect = "SQLITE"
#paths must be relative to running directory
sqlite_extensions = ["../../my-todo-app/api/plugins/uuid"]
migrations_path = "../../my-todo-app/api/migrations"

[service.auth]
requesting_party = "localhost"
requesting_party_name = "triceratask.com"
requesting_party_origin = "http://localhost:5173" #Origin of the client. http://localhost:5173
identifier = "username"
data_source = "triceratask_ds"

[[service.entities]]
name = "todo"
# guards = [
#   { name = "Permissions Error", if_expr = "headers(\"user_uuid\") != input(\"created_by\")", then_msg = "Permission Denied - You can only manage your own todos." },
# ]
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["All"]  },
  { name = "uuid", scalar = "String", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"] },
  { name = "title", scalar = "String", required = true },
  { name = "description", scalar = "String", required = true },
  { name = "completed", scalar = "Boolean", required = true },
  { name = "created_at", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "updated_at", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "completed_at", scalar = "String", required = false, exclude_from_input = ["All"] },
  { name = "created_by", scalar = "String", required = true, exclude_from_input = ["UpdateOne", "UpdateMany"] },
  { name = "updated_by", scalar = "String", required = true },
  { name = "completed_by", scalar = "String", required = false, exclude_from_input = ["All"] },
]

[service.entities.data_source]
from = "triceratask_ds"
[service.entities.data_source.resolvers]
[service.entities.data_source.resolvers.find_one]
[[service.entities.data_source.resolvers.find_one.guards]]
name = "Permissions Error"
if_expr = "headers(\"user_uuid\") != input(\"created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

[service.entities.data_source.resolvers.find_many]
[[service.entities.data_source.resolvers.find_many.guards]]
name = "Permissions Error"
if_expr = "headers(\"user_uuid\") != input(\"created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

[service.entities.data_source.resolvers.create_one]
[[service.entities.data_source.resolvers.create_one.guards]]
name = "Permissions Error"
if_expr = "headers(\"user_uuid\") != input(\"created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

[service.entities.data_source.resolvers.update_one]
[[service.entities.data_source.resolvers.update_one.guards]]
name = "Permissions Error"
if_expr = "headers(\"user_uuid\") != input(\"query.created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

[service.entities.data_source.resolvers.update_many]
[[service.entities.data_source.resolvers.update_many.guards]]
name = "Permissions Error"
if_expr = "headers(\"user_uuid\") != input(\"query.created_by\")"
then_msg = "Permission Denied - You can only manage your own todos."

