[service]
name = "todos"
port = 5555

[[service.data_sources]]
[service.data_sources.SQL]
name = "devoyage_platform"
uri = "sqlite:/home/nickisyourfan/Desktop/DEV/my-todo-app/api/todos.db"
dialect = "SQLITE"

[[service.entities]]
name = "todo"
fields = [
  { name = "id", scalar = "Int", required = true, exclude_from_input = ["CreateOne", "UpdateOne", "UpdateMany"]  },
  { name = "title", scalar = "String", required = true },
  { name = "description", scalar = "String", required = true },
  { name = "completed", scalar = "Boolean", required = true },
  { name = "created_at", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "updated_at", scalar = "String", required = true, exclude_from_input = ["All"] },
  { name = "completed_at", scalar = "String", required = false, exclude_from_input = ["CreateOne", "UpdateMany"] }
]


